FROM node:20-alpine AS builder

WORKDIR /app

# Copy root config files
COPY package.json pnpm-lock.yaml nest-cli.json tsconfig*.json ./

# Install dependencies
RUN npm install -g pnpm && \
    pnpm install --frozen-lockfile

# Copy service files and shared config
COPY apps/producer ./apps/producer
# COPY apps/shared ./apps/shared  # If you have shared code
# COPY libs ./libs                # If using libraries

# Build specific project
RUN pnpm build producer

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/apps/producer/main.js"]